## Numpy

Импортировать NumPy под именем np

In [1]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создать вектор размера 10, заполненный единицами

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Создать вектор размера 10, заполненный числом 2.5

In [9]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [8]:
x = np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Развернуть вектор (первый становится последним)

In [9]:
x[::-1]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [13]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [2]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

Создать 3x3 единичную матрицу

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Создать массив 3x3x3 со случайными значениями

In [4]:
np.random.rand(3,3,3)

array([[[0.36630601, 0.36598616, 0.22416071],
        [0.93724133, 0.35755585, 0.90326593],
        [0.86241413, 0.48657701, 0.89172392]],

       [[0.42743041, 0.3810381 , 0.64686702],
        [0.12706957, 0.23591517, 0.53685665],
        [0.64463374, 0.89508866, 0.07026988]],

       [[0.03797057, 0.26232141, 0.93180725],
        [0.83301833, 0.03793509, 0.11094976],
        [0.36111823, 0.74518989, 0.65535842]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [6]:
np.mean(np.random.random(30))

0.49773245473942207

Перемножить матрицы 5x3 и 3x2

In [7]:
np.random.rand(5,3) @ np.random.rand(3,2)

array([[0.35335693, 0.08014491],
       [1.45460487, 0.34305314],
       [1.14106624, 0.19730382],
       [1.13177419, 0.24025558],
       [0.75915686, 0.16369746]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [12]:
y=np.linspace(0,1,12)[1:-1]
y

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

Заменить максимальный элемент на ноль

In [13]:
y[y.argmax()]=0
y

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.        ])

Преобразовать массив из float в int

In [19]:
z=np.array([0.1,2.12,3.24])
z.astype(int)

array([0, 2, 3])

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [33]:
tenp = np.random.randint(1,100,20).reshape(10,2)
np.sqrt(np.sum((tenp[None, :] - tenp[:, None])**2, -1))

array([[ 0.        , 31.06444913, 74.24284477,  9.21954446, 46.69047012,
        26.40075756, 64.07807737, 47.        , 46.01086828, 17.02938637],
       [31.06444913,  0.        , 94.06912352, 22.        , 61.84658438,
        49.39635614, 93.96275858, 57.98275606, 56.60388679, 33.54101966],
       [74.24284477, 94.06912352,  0.        , 80.45495634, 32.80243893,
        47.88527958, 48.02082881, 38.94868419, 40.31128874, 90.0777442 ],
       [ 9.21954446, 22.        , 80.45495634,  0.        , 50.92150823,
        32.80243893, 73.1641989 , 49.81967483, 48.66210024, 17.        ],
       [46.69047012, 61.84658438, 32.80243893, 50.92150823,  0.        ,
        22.20360331, 55.15432893,  8.06225775,  9.        , 63.63961031],
       [26.40075756, 49.39635614, 47.88527958, 32.80243893, 22.20360331,
         0.        , 48.01041554, 25.49509757, 25.05992817, 42.72001873],
       [64.07807737, 93.96275858, 48.02082881, 73.1641989 , 55.15432893,
        48.01041554,  0.        , 62.96824597

Случайно расположить p элементов в 2D массив

In [55]:
p = np.random.randint(1,10,5) #набор p элементов
b = np.random.choice(15,5,replace=False) #позиции для замены
a = np.random.randint(50,100,size=(3,5)) # 2D массив
a.flat[b]=p
a

array([[54,  1, 97,  3, 77],
       [50, 65, 58,  2, 63],
       [93, 98,  3,  5, 85]])

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [59]:
c = np.array([1,2,3,4,5])
d = np.zeros(3*(len(c)-1)+len(c))
d[::4]=c
d

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

Найти наиболее частое значение в массиве

In [78]:
f = np.random.randint(1,10,15)
np.bincount(f).argmax()

4

Найти n наибольших значений в массиве

In [64]:
g = np.random.randint(1,100,20)
n = 4
np.sort(g)[::-1][:n]

array([90, 88, 83, 80])

## Pandas - изучение данных

In [79]:
import pandas as pd

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [83]:
food = pd.read_csv('food.tsv', sep='\t')

Посмотреть первые 5 записей

In [88]:
food.head(5)

code                                                url  \
0   3087  http://world-en.openfoodfacts.org/product/0000...   
1   4530  http://world-en.openfoodfacts.org/product/0000...   
2   4559  http://world-en.openfoodfacts.org/product/0000...   
3  16087  http://world-en.openfoodfacts.org/product/0000...   
4  16094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [87]:
food.shape[0]

356027

Сколько столбцов в наборе данных?

In [89]:
food.shape[1]

163

Напечатайте все названия столбцов

In [90]:
food.columns.values

array(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity', 'packaging', 'packaging_tags',
       'brands', 'brands_tags', 'categories', 'categories_tags',
       'categories_en', 'origins', 'origins_tags', 'manufacturing_places',
       'manufacturing_places_tags', 'labels', 'labels_tags', 'labels_en',
       'emb_codes', 'emb_codes_tags', 'first_packaging_code_geo',
       'cities', 'cities_tags', 'purchase_places', 'stores', 'countries',
       'countries_tags', 'countries_en', 'ingredients_text', 'allergens',
       'allergens_en', 'traces', 'traces_tags', 'traces_en',
       'serving_size', 'no_nutriments', 'additives_n', 'additives',
       'additives_tags', 'additives_en', 'ingredients_from_palm_oil_n',
       'ingredients_from_palm_oil', 'ingredients_from_palm_oil_tags',
       'ingredients_that_may_be_from_palm_oil_n',
       'ingredients_that_may_be_from_palm_oil',
   

Какое название у 105 столбца?

In [91]:
food.columns.values[104]

'-glucose_100g'

Какой тип наблюдений в 105 столбце?

In [92]:
food['-glucose_100g'].dtypes

dtype('float64')

Как проиндексирован набор данных?

In [101]:
food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356027 entries, 0 to 356026
Columns: 163 entries, code to water-hardness_100g
dtypes: float64(107), object(56)
memory usage: 442.8+ MB


Каково значение имени продукта в 19-м наблюдении?

In [100]:
food.iloc[18]['product_name']

'Lotus Organic Brown Jasmine Rice'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [121]:
url='https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(url, sep = '\t')

Как много продуктов стоят более чем $10.00?

In [123]:
chipo['item_price'] = chipo['item_price'].replace( '[\$,]','', regex=True ).astype(float)
chipo[chipo['item_price'] > 10].shape[0]

1130

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [132]:
chipo[['item_name','item_price']].sort_values(by=['item_price'])

item_name  item_price
1140                 Bottled Water        1.09
821                    Canned Soda        1.09
3926                   Canned Soda        1.09
107                    Canned Soda        1.09
2562                   Canned Soda        1.09
473                    Canned Soda        1.09
2961                   Canned Soda        1.09
1457                   Canned Soda        1.09
2545                 Bottled Water        1.09
2544                   Canned Soda        1.09
1945                   Canned Soda        1.09
3897                   Canned Soda        1.09
3361                 Bottled Water        1.09
2538                   Canned Soda        1.09
2981                 Bottled Water        1.09
1948                   Canned Soda        1.09
2922                 Bottled Water        1.09
180                    Canned Soda        1.09
438                    Canned Soda        1.09
434                    Canned Soda        1.09
87                   Bottled Water        1.09
246                    Canned Soda        1.09
247                    Canned Soda        1.09
248                    Canned Soda        1.09
1396                   Canned Soda        1.09
251                    Canned Soda        1.09
414                    Canned Soda        1.09
2520                   Canned Soda        1.09
3434                   Canned Soda        1.09
1953                   Canned Soda        1.09
...                            ...         ...
2510                  Chicken Bowl       22.50
1923            Chicken Salad Bowl       22.50
1429                  Chicken Bowl       22.50
2419            Chicken Salad Bowl       22.50
213             Chicken Salad Bowl       22.50
816             Chicken Salad Bowl       22.50
4423                  Chicken Bowl       22.50
3507            Chicken Salad Bowl       22.50
633             Chicken Salad Bowl       22.50
2954                 Steak Burrito       22.96
4427                    Steak Bowl       23.50
506                  Carnitas Bowl       23.50
3754                    Steak Bowl       23.50
1753                 Steak Burrito       23.50
4307                    Steak Bowl       23.50
1566                    Steak Bowl       23.50
281               Steak Salad Bowl       23.78
613               Steak Salad Bowl       23.78
3334                    Steak Bowl       26.07
1514                  Chicken Bowl       26.25
3634               Chicken Burrito       26.25
3636               Chicken Burrito       26.25
3603                 Steak Burrito       27.75
1255                 Steak Burrito       27.75
409                   Chicken Bowl       32.94
3601                Veggie Burrito       33.75
3602               Chicken Burrito       35.00
1254               Chicken Burrito       35.00
3480                 Carnitas Bowl       35.25
3598  Chips and Fresh Tomato Salsa       44.25

[4622 rows x 2 columns]

Отсортировать по имени предмета

In [130]:
chipo.sort_values(by=['item_name'])

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
4527      1800         1  6 Pack Soft Drink   
4522      1798         1  6 Pack Soft Drink   
3806      1525         1  6 Pack Soft Drink   
2389       949         1  6 Pack Soft Drink   
3132      1248         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
639        264         1  6 Pack Soft Drink   
1026       422         1  6 Pack Soft Drink   
...        ...       ...                ...   
2996      1192         1       Veggie Salad   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
1694       686         1       Veggie Salad   
2756      1094         1       Veggie Salad   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description  item_price  
3389                                        [Diet Coke]       12.98  
341                                         [Diet Coke]        6.49  
1849                                             [Coke]        6.49  
1860                                        [Diet Coke]        6.49  
2713                                             [Coke]        6.49  
3422                                             [Coke]        6.49  
553                                         [Diet Coke]        6.49  
1916                                        [Diet Coke]        6.49  
1922                                             [Coke]        6.49  
1937                                        [Diet Coke]        6.49  
3836                                             [Coke]        6.49  
298                                            [Sprite]        6.49  
1976                                        [Diet Coke]        6.49  
1167                                             [Coke]        6.49  
3875                                     

Сколько было заказано самого дорогого предмета?

In [133]:
chipo.loc[chipo['item_price'].idxmax(), 'quantity']

15

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [139]:
chipo[chipo['item_name']=='Veggie Salad Bowl']['quantity'].shape[0]

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [143]:
chipo[(chipo['item_name']=='Canned Soda')& (chipo['quantity']>1)].shape[0]

20